name: GitHub Pages

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependencies
        run: |
          npm install -g markdown-to-html
          
      - name: Build
        run: |
          mkdir _site
          markdown-to-html README.md > _site/index.html
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 